- lib/CMakeLists.txt
- yhwrap/CMakeLists.txt
- yhwrap/version.rc.in
> cmake: do windows versioninfo correctly

- src/main.c
Make sure that keepalive is handled correctly also in CLI mode.
> Fix noninteractive keepalive

- .travis.yml
- common/parsing.c
- common/parsing.h
- src/CMakeLists.txt
- src/commands.c
- yhauth/main.c
- ykyh/ykyh.c
Various improvements to `ykyh` and `yhauth`.
> Ykyh update

- lib/yubihsm.h
- src/commands.c
> HSM-234: shell: Replaced unprintable characters in label with '.'

- yhauth/cmdline.ggo
- yhauth/main.c
- ykyh/ykyh.c
- ykyh/ykyh.h
Improvements to `yhauth` to
- correctly parse the touch value in the `list` command
- add a `calculate` command
> Yhauth fixes

- lib/yubihsm_winhttp.c
This makes the winhttp layer a bit saner by storing less data in the backend state.
> winhttp: try to make winhttp backend more thread-safe

- src/main.c
> tool: correctly free up connector_list resources

- src/main.c
fixes issue from #88 since I was to quick in merging #92
> tool: set n_connectors to 0 at end of main

- lib/lib_util.c
- lib/tests/test_usb_url.c
more code for #89 since I was to quick merging #93
> lib: when failing to parse serial print error and return false

- pkcs11/util_pkcs11.c
as long as it's set to false, just accept it
> p11: make the module accepts CKA_SIGN_RECOVER/CKA_VERIFY_RECOVER

- pkcs11/util_pkcs11.c
this was missed in an earlier refactor and the length was returned
unchanged
> pkcs11: when getting a pkcs11 attribute fails the length is -1

- pkcs11/tests/ecdh_derive_test.c
- pkcs11/util_pkcs11.c
- pkcs11/yubihsm_pkcs11.c
Noticed by @a-dma in my last PR.
Also fixing a few additional instances of this typo in the
tree while at it.
> spelling: fixing a couple of to -> too

- src/commands.c
- src/main.c
- src/yubihsm-shell.h
This should be merged before asym-auth as that branch removes the check for session id in the library
> Remove session id assumptions

- lib/yubihsm_winhttp.c
Added this to the winhttp backend, was added to the curl backend earlier
> Use has_device in parsed status report

- src/CMakeLists.txt
- src/commands.c
- src/commands.h
- src/main.c
since there is no released YubiHSM with this functionality (yet) put
them behind an experimental compilation flag
> tool: put the asymmetric auth commands behind ifdef

- lib/error.c
- lib/yubihsm.c
- lib/yubihsm.h
tool support for this comes for free
> lib: add support for the algo-toggle option

- src/cmdline.ggo
- src/commands.c
- src/commands.h
- src/main.c
get_device_pubkey is part of this feature
this is maybe not ideal, but starting to filter the commandline.ggo for a temporary ifdef feels over the top.
> tool: more ifdefs for asymmetric auth feature

- src/commands.c
- src/commands.h
- src/main.c
this is then "session ykopen id name password"
> shell: instead of "yk:" syntax for specifying ykhsmauth use own command

- ykhsmauth/ykhsmauth.c
> ykhsmauth: fix issue with matching the reader with the wanted string

- aes_cmac/aes.c
- aes_cmac/aes.h
- aes_cmac/aes_cmac.c
- aes_cmac/aes_cmac.h
- lib/yubihsm.c
We should probably use the EVP interface instead of the low-level and deprecated AES api
> Refactored using EVP interface

- examples/asym_auth.c
- examples/import_authkey.c
These tests were improved to also test capabilites handling
> Improved testing of explicit capabilites

- .github/workflows/build_and_test.yml
This might fix build errors with Ubuntu 16.04
> Remove the upgrade option when installing pip3

- examples/CMakeLists.txt
- examples/attest.c
> Verify signature on attestations

- CMakeLists.txt
- src/CMakeLists.txt
- src/cmdline.ggo
- src/commands.c
- src/commands.h
- src/main.c
- src/yubihsm-shell.h
> Add option to disable ykhsmauth module

- aes_cmac/aes.c
- examples/asym_auth.c
- examples/echo.c
- lib/lib_util.c
- lib/tests/CMakeLists.txt
- lib/yubihsm.c
- lib/yubihsm_curl.c
- lib/yubihsm_libusb.c
- lib/yubihsm_usb.c
- lib/yubihsm_winhttp.c
- lib/yubihsm_winusb.c
- src/cmdline.ggo
- src/commands.c
- src/main.c
Move device error handling into send_plain_msg and _send_secure_msg to remove code duplication
> Device error handling improvements

- .github/workflows/macos_build.yml
- .github/workflows/ubuntu_build.yml
- .github/workflows/windows_build.yml
Fix Windows build in Github Actions. Add MacOS and Ubuntu builds in Github Actions
> Update Github Actions

- CMakeLists.txt
This is in response to https://github.com/Yubico/yubihsm-shell/issues/237
> Added -Wno-missing-braces

- pkcs11/yubihsm_pkcs11.c
> Add CKA_CERTIFICATE_TYPE in C_FindObjectsInit

- src/commands.c
- src/commands.h
- src/main.c
Adresses https://github.com/Yubico/yubihsm-shell/issues/204
> Support specifying AES authentication keys explicitly

- aes_cmac/aes_cmac.c
- aes_cmac/aes_cmac.h
Removed unused mac field, and now using aes_cbc_encrypt
> Simplify aes_cmac

- .github/workflows/build_and_test.yml
- pkcs11/util_pkcs11.c
- pkcs11/util_pkcs11.h
- pkcs11/yubihsm_pkcs11.c
- pkcs11/yubihsm_pkcs11.h
Implement support for editing CKA_ID and CKA_LABEL through the use of opaque meta objects
> Opaque Meta Object

- pkcs11/util_pkcs11.c
- pkcs11/yubihsm_pkcs11.c
> PKCS11: Meta opaque: Mitigate a potential stackbuffer overflow

- common/util.c
- common/util.h
- src/commands.c
- src/main.c
> Support PEM-coded keys for asym auth

- pkcs11/util_pkcs11.c
- pkcs11/util_pkcs11.h
- pkcs11/yubihsm_pkcs11.c
- pkcs11/yubihsm_pkcs11.h
Add support for separate attributes for public and private key
> Meta opaque pubkey

- .github/workflows/release.yml
- .github/workflows/windows_build.yml
GithubActions: Update Windows build scripts
> GithubActions: Update Windows build scripts

- .github/workflows/build_and_test.yml
- .github/workflows/integration_test.yml
* Reduce number of full testing platforms
* Move integration tests to a separate workflow
* Run integration tests on a schedule once a week
> Githubactions

- lib/internal.h
- pkcs11/util_pkcs11.c
- pkcs11/util_pkcs11.h
- pkcs11/yubihsm_pkcs11.c
- pkcs11/yubihsm_pkcs11.h
Meta Object: Match domains when searching for meta object by target
> Meta object domains

- pkcs11/yubihsm_pkcs11.c
> Add support for CKA_EXTRACTABLE for PKCS11 imported certificates

- pkcs11/yubihsm_pkcs11.c
Small typo I noticed while looking through the repository.
> Fix typo in user type check

- src/tests/wrapped_tests.sh
Adds tests for https://github.com/Yubico/yubihsm-shell/pull/351
> Test signing with imported vs wrapped key

- pkcs11/tests/CMakeLists.txt
This will require https://github.com/YubicoLabs/pkcs11test/pull/9 to be merged first (tests fail until then).
> pkcs11: enable secret key tests

- .github/workflows/build_and_test.yml
- .github/workflows/build_and_test_windows.yml
- .github/workflows/integration_test.yml
- .github/workflows/release.yml
- resources/release/macos/make_release_binaries.sh
> Githubactions paths

- .github/workflows/build_and_fuzz.yml
- pkcs11/CMakeLists.txt
Fix the failing fuzzing workflow.
> Fix fuzzing workflow
