Yubico/yubihsm-shell

lib/yubihsm_winhttp.c
parse_status_data() uses strtok_r which requires a null terminated string.
This also mirrors the code in lib/yubihsm_curl.c.
(Found while playing with libfuzzer)
=> Make sure the buf that parse_status_data() get is always null terminated

src/main.c
Make it possible to generate authkey specifying all the capabilities in their string form. Here's one example of what does not work with the current master, and that this PR fixes:
```
yubihsm> put authkey 1 0x03 "NEW MAIN AUTHKEY2" 0xffff change-authentication-key,create-otp-aead,decrypt-oaep,decrypt-otp,decrypt-pkcs,delete-asymmetric-key,delete-authentication-key,delete-hmac-key,delete-opaque,delete-otp-aead-key,delete-template,delete-wrap-key,derive-ecdh,export-wrapped,exportable-under-wrap,generate-asymmetric-key,generate-hmac-key,generate-otp-aead-key,generate-wrap-key,get-log-entries,get-opaque,get-option,get-pseudo-random,get-template,import-wrapped,put-asymmetric-key,put-authentication-key,put-mac-key,put-opaque,put-otp-aead-key,put-template,put-wrap-key,randomize-otp-aead,reset-de …
```
=> Make it possible to generate authkey

src/main.c
Added support for EDDSA signatures from the command line, using the already-implemented --action=sign-ecdsa command. The required parameters are identical, but --action=sign-eddsa reports "Command not implemented".
=> Implement --action=sign-eddsa

CMakeLists.txt, examples/CMakeLists.txt, lib/CMakeLists.txt, lib/tests/CMakeLists.txt, pkcs11/CMakeLists.txt, src/CMakeLists.txt, yhauth/CMakeLists.txt, yhwrap/CMakeLists.txt
Using CMAKE_CURRENT_SOURCE_DIR allows this project to be included in other cmake projects where CMAKE_SOURCE_DIR may not be what is expected here
I didn't change a few targets like `dist` (because not really interesting from a cmake reuse standpoint) and `cppcheck` (because I don't have a good way of checking it at the moment) so there might be other fine tuning that still could be done to improve the CMAKE_SOURCE_DIR vs CMAKE_CURRENT_SOURCE_DIR
=> Use CMAKE_CURRENT_SOURCE_DIR instead of CMAKE_SOURCE_DIR

CMakeLists.txt
When integrating the yubihsm-shell repository in to other cmake projects oftentimes only the yubihsm library is required. However, the CMakeLists.txt will bring in a number of dependencies needed for the various tools, such as libedit, help2man, gengetopt, etc., that are unneeded for just building the library.
Add a cmake option to enable a library only build so that these additional dependencies are not required by cmake when a parent cmake project just wants to link against libyubihsm.
=> Add a library only build option

CMakeLists.txt, aes_cmac/aes.c, common/hash.c, src/main.c
build: fix 32-bit Windows builds with mingw32/gcc7
shell: apply stdcall calling convention for Windows callback on x86
=> Windows x86 build fixes

src/main.c
openssl gets sad if a signal hits while that function is waiting for
input from the user and will both be interrupted and the actual input
will be dumped on the prompt.
Also move the blocking of keepalive further into when we actually make a
call to the device rather than being around the whole collection and
validation logic.
=> tool: stop the timer for keepalive while we do EVP_read_pw_string()

src/main.c
Hi, 
I found a bug of yubihsm-wrap command.
I think wrap_id and object_id of args of yh_com_get_wrapped is switched.
https://github.com/Yubico/yubihsm-shell/blob/master/src/main.c#L2138-L2164
https://github.com/Yubico/yubihsm-shell/blob/master/src/commands.c#L1008-L1026
https://github.com/Yubico/yubihsm-shell/blob/master/lib/yubihsm.h#L1557-L1559
=> switch wrap_id and object_id of args of yh_com_get_wrapped

pkcs11/tests/CMakeLists.txt, pkcs11/tests/engine_tests.sh, src/tests/tests.sh
#51 fixed build on FreeBSD but it did not fix tests.  After this patch, all tests passed.
```
[0/1] Running tests...
Test project /tmp/yubihsm-shell-master/build
Start  1: parsing
1/25 Test  #1: parsing ..........................   Passed    0.00 sec
Start  2: pbkdf2
2/25 Test  #2: pbkdf2 ...........................   Passed    0.02 sec
Start  3: attest
3/25 Test  #3: attest ...........................   Passed    0.44 sec
Start  4: generate_ec
4/25 Test  #4: generate_ec ......................   Passed    0.30 sec
Start  5: generate_hmac
5/25 Test  #5: generate_hmac ....................   Passed    0.19 sec
Start  6: import_authkey
6/25 Test  #6: import_authkey ...................   Passed    0.22 sec
Start  7: import_rsa
7/25 Test  #7: import_rsa .......................   Passed    0.36 …
```
=> Fix tests on FreeBSD.

.travis.yml, common/util.c, common/util.h, examples/CMakeLists.txt, pkcs11/CMakeLists.txt, src/commands.c, src/tests/wrapped_tests.sh, yhwrap/CMakeLists.txt
- Correctly wrap ed25519 key in `yubihsm-wrap`
- Add Ubuntu Bionic to Travis
- Add a test for wrapping ed25519 credentials (on Bionic only)
- Fix printing ed25519 keys in `yubihsm-shell`
=> Wrap ed25519

CMakeLists.txt
Setting FORTIFY_SOURCE in the latest mingw gcc breaks our build and requires that we take an unnecessary dynamic dependency.  It never had much effect before, so it has been removed for Windows builds.
=> build: mingw/gcc 9.2.0 has broken FORTIFY_SOURCE

src/main.c
The error I was getting during the builds for Fedora rawhide:
```
/builddir/build/BUILD/yubihsm-shell-2.0.2/src/main.c: In function 'yubihsm_complete':
/builddir/build/BUILD/yubihsm-shell-2.0.2/src/main.c:1277:16: error: 'cursoro' may be used uninitialized in this function [-Werror=maybe-uninitialized]
1277 |         return complete_arg(el, args, argv[i], cursoro);
|                ^
/builddir/build/BUILD/yubihsm-shell-2.0.2/src/main.c:1173:22: note: 'cursoro' was declared here
1173 |   int argc, cursorc, cursoro;
|                      ^
lto1: all warnings being treated as errors
```
(but probably because of some different flags, only on s390x architecture)
=> Avoid warnings with some gcc versions

CMakeLists.txt
dotnet core cannot load our yubihsm-pkcs11.dylib on MacOS Catalina 10.15.5, even though other tools like pkcs11-tool can. This commit fixes that problem. We had the same issue when porting libykcs11.dylib over to cmake. It seems to be a recent problem, earlier testing with dotnet has worked.
=> Set the CMP0042 policy to make dotnet able to load yubihsm-pkcs11

lib/internal.h, lib/scp.h, lib/yubihsm.c, lib/yubihsm_curl.c, lib/yubihsm_usb.c, lib/yubihsm_winhttp.c
this allows an http load balancer to keep track of what requests belong
together and need to be stickied on a connector and what can go to a new
one
=> lib: add a session identifier for the backend

lib/lib_util.c, lib/tests/test_usb_url.c
Note: that this might break existing scripts since this changes behaviour.
Note 2: there are other strtoul() in this file still parsing with the
old behaviour, i.e. allowing 0x and 0 prefix for hex and octal.
Fixes #89
=> lib: explicitly parse serial as base 10

pkcs11/tests/ecdh_derive_test.c
This test does the same as validate_ecdh_attributes() but 
provides to small buffers for all values and makes sure
that the return code is CKR_BUFFER_TOO_SMALL and that the
template ulValueLen is CK_UNAVAILABLE_INFORMATION for
each attribute as it should be.
=> tests: add check_attributes_buffer_to_small() unit test

.github/workflows/macos_build.yml, CMakeLists.txt
actions: go back to suppressing the nullable warnings on macos
This way we can build with both system curl and brew curl
(also removed -DWITHOUT_YKYH=1 since it did not exist as a cmake variable)
=> actions: go back to suppressing the nullable warnings on macos

src/main.c
At least, wrapped keys, with metadata and base64, can easily be > 4096
bytes (5016 for a wrapped RSA:4096 object I have here).
I think for reading files a growable heap buffer makes more sense, but
this is a cheap hack to get me running again.
=> Increase size of CLI work buffer

.github/workflows/build_and_test.yml
Our tests continually fail on the mac environment in github actions since this weekend, for now disable them.
=> Disable CI tests on mac

common/parsing.c, common/parsing.h, common/util.c, common/util.h, pkcs11/CMakeLists.txt, pkcs11/yubihsm_pkcs11.c, src/main.c, yhauth/main.c
parse_hex() and hex_decode() both implement a hex decoder, we had an
additional hex_decode() in yhauth as well that also gets removed and use
the one in common.
=> common: move hex_decode() to parsing.c and remove parse_hex()

lib/scp.h
We were already limiting ourselves to the correct size, the extra buffer space was unused
=> Corrected buffer sizes

lib/yubihsm.c
On Windows, load the backend using LoadLibraryEx with an absolute path derived from the path to libyubihsm and LOAD_WITH_ALTERED_SEARCH_PATH. This allows libyubihsm to find the backend DLL without having to set PATH, even in scenarios where it was loaded indirectly via dynamic loading of yubihsm_pkcs11, for example.
=> Use LoadLibraryEx

lib/yubihsm.h, lib/yubihsm_curl.c, pkcs11/cmdline.ggo, pkcs11/yubihsm_pkcs11.c
Add support for libcurl cert and key to use client-side certificates as authentication.
Add support for shell like variable expansion.
Add libcurl noproxy option.
=> Additional curl options

src/main.c
Fixes a segfault when pressing enter at the Enter password prompt:
yubihsm> session open 1
Enter password:
Program received signal SIGSEGV, Segmentation fault.
get_input_data (name=0x7f7ffffbbad5 "-", out=0xb7d69f67000 "", len=0x7f7ffffbdd08, fmt=fmt_password)
at /user/kode/yubihsm-shell/src/main.c:1488
1488          if (out[data_len - 1] == '\n') {
Current language:  auto; currently minimal
(gdb) p data_len
$1 = 0
(gdb)
=> shell: do not index array out of bounds

src/main.c, src/yubihsm-shell.h
Command completion for 'set informat' and 'set outformat' for the default option. It could only be typed in manually before.
=> Fix command completion for default format

pkcs11/yubihsm_pkcs11.c
The translation of the `CKA_{DECRYPT,ENCRYPT}` attributes to the
corresponding `{un}wrap-data` capabilities for wrap keys is missing from
`C_GenerateKey`, but present in `C_CreateObject`. Remedy this by also
handling the attributes in `C_GenerateKey`.
=> pkcs11: handle CKA_{DECRYPT,ENCRYPT} when generating wrap keys

pkcs11/yubihsm_pkcs11.c
Input data and output length pointers may not be NULL.
=> pkcs11: validate encrypt/decrypt arguments

CMakeLists.txt, cmake/cppcheck.cmake
Fix for https://github.com/Yubico/yubihsm-shell/issues/220
=> Don't use absolute path for cppcheck

examples/p11_generate_rsa.c, pkcs11/tests/CMakeLists.txt, pkcs11/tests/common.c, pkcs11/tests/common.h, pkcs11/tests/ecdh_derive_test.c, pkcs11/tests/rsa_enc_test.c, pkcs11/util_pkcs11.c
Introduces a common source file for the PKCS#11 tests to deduplicate
helper functions used to load the module, set up a session, etc.
=> pkcs11: consolidate common test functions

debian/changelog
Fixes:
```
dpkg-gencontrol: warning:     debian/changelog(l5): badly formatted trailer line
LINE:  -- Aveen Ismail <aveen.ismail@yubico.com> Mon, 1 Mar 2021 16:28:03 +0100
dpkg-genbuildinfo: warning:     debian/changelog(l11): badly formatted trailer line
LINE:  -- Aveen Ismail <aveen.ismail@yubico.com> Tue, 13 Oct 2020 13:37:10 +0100
```
=> debian fix changelog trailer lines

debian/control
dh_auto_configure fails in pbuilder without these deps
=> debian/ add missing Build-Depends

debian/changelog
The format of the debian package is native
```
$ cat debian/source/format
3.0 (native)
```
change version number format to match
=> fix debian changelog version numbers (native pkg)

CMakeLists.txt
This is added to suppress the error during the build process.
=> Naimul - Added Wno-missing-field-initializers 

CMakeLists.txt, src/main.c
Fix apparent issues with the source on RHEL 7.9, and only set initializer flags on Linux, as they are not needed on macos
=> Avoid RHEL 7.9 issues

lib/yubihsm_curl.c
clang-15 and later will otherwise issue warnings under `-Wstrict-prototypes -pedantic`.
=> lib/curl: backend_create() explicitly takes no arguments

pkcs11/yubihsm_pkcs11.c
The C_GetInfo library version is already done this way
=> Multiply FW minor version by 10 instead of 100 to avoid overflow

resources/tests/bash/test_eckey.sh, resources/tests/bash/test_edkey.sh, resources/tests/bash/test_hmackey.sh, resources/tests/bash/test_otpaeadkey.sh, resources/tests/bash/test_rsakey.sh, resources/tests/bash/test_wrapkey.sh
While here, fix an incorrect variable name and missing newlines at EOF.
=> tests: ensure that variables are set before use

src/commands.c
adding a "," between sequence and label is more consistent and simplifies parsing of list-objects output.
=> fix list-object output formatting

lib/yubihsm.pc.in, ykhsmauth/ykhsmauth.pc.in
This commit fixes `*.pc.in` files to use `YUBIHSM_INSTALL_INC_DIR` instead of `INSTALL_INC_DIR`. The resulting pkg-config files have the correct paths for compiler flags.
=> Fix typos in pkg-config templates

.github/workflows/build_and_test.yml, .github/workflows/release.yml, resources/release/macos/make_release_binaries.sh
Update release workflow and MacOS release script
=> Githubactions

pkcs11/util_pkcs11.c
Having problems signing with EdDSA on YubiHSM2 via PKCS11. Getting an 
pkcs11:p11prov_Sign:The size of plaintext input data to a cryptographic operation is invalid (Out of range):interface.gen.c:679:Error returned by C_Sign error
As I understand the PKCS11 v3.0 spec, the 1024 bit limit (note by "adma" in line 2228) applies only to "ECDSA without hashing" (CKM_ECDSA) as it only processes a hash value.
see: https://docs.oasis-open.org/pkcs11/pkcs11-curr/v3.0/os/pkcs11-curr-v3.0-os.html#_Toc30061189
EdDSA does not have this limit, so the size of "op_info->buffer" should be the limiting factor
see: https://docs.oasis-open.org/pkcs11/pkcs11-curr/v3.0/os/pkcs11-curr-v3.0-os.html#_Toc30061191
=> fix buffer_length check for EdDSA in util_pkcs11.c

pkcs11/yubihsm_pkcs11.c
This problem fails the build on 32 b architectures:
```
/usr/bin/gcc -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection  -Wno-error=deprecated-declarations -flto -Wno-missing-braces -Wno-missing-field-initializers -g -Wl,-z,relro -Wl,--as-needed  -Wl,-z,pack-relative-relocs -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld-errors -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 …
```
=> pkcs11: Fix format string

common/util.c
A newline is written to stdout in command-line mode. This causes issues with binary output. For example:
echo -n 0123456789abcdef | yubihsm-shell -p password -a encrypt-aesecb -i 123 | yubihsm-shell -p password -a decrypt-aesecb -i 123
Other commands have similar issues (e.g. `-a get-pseudo-random --count=16 --outformat binary | wc -c` outputs 17)
This patch simply drops the newline when writing binary output to stdout.
=> fix binary output to stdout

CMakeLists.txt, lib/CMakeLists.txt, lib/yubihsm.c
Use MSVC compatible unused parameter method
Add MSVC static runtime on static build
Exclude openssl compat for WIN32_BCRYPT builds
=> CNG Provider Build Updates

pkcs11/tests/asym_wrap_test.c
`C_WrapKey` and `C_UnwrapKey` use `CK_ULONG` for the wrapped key size, which isn't the same as `size_t` on all architectures.  This caused "passing argument ... from incompatible pointer type" errors on Debian i386.
=> Fix asym_wrap_test on 32-bit architectures

src/commands.c
On some architectures, such as Debian's 32-bit armel and armhf architectures after their recent migration to 64-bit `time_t`, the `time_t` and `long` types are not the same size.  Fix `yh_com_benchmark` to avoid assuming that they are.
=> Don't assume that sizeof(time_t) == sizeof(long)

.github/workflows/build_and_fuzz.yml, .github/workflows/push_fuzzing_msan_container.yml, CMakeLists.txt, cmake/Fuzzing.cmake, cmake/SecurityFlags.cmake, examples/CMakeLists.txt, lib/CMakeLists.txt, lib/fuzz/fuzz_send_plain_msg.cc, lib/fuzz/fuzz_send_secure_msg.cc, lib/fuzz/yubihsm_fuzz.cc, lib/fuzz/yubihsm_fuzz.h, lib/internal.h, lib/scp.h, lib/yubihsm.c, lib/yubihsm.h, pkcs11/CMakeLists.txt, pkcs11/fuzz/fuzz_get_attribute_value.cc, pkcs11/util_pkcs11.c, pkcs11/yubihsm_pkcs11.c, resources/fuzzing/Docker.fuzzing_msan, src/CMakeLists.txt
This PR includes various changes to support fuzzing.
=> Initial fuzzing code

yubihsm-auth/main.c
YubiHSM Auth: Improve error message when YubiKey is too old to support yubihsm-auth
=> YubiHSM Auth: Improve error message

src/commands.c
Public wrap keys also have delegated capabilities. This PR extends `get objectinfo` to also report it for them.
=> Report delegated capabilities for public-wrap-key too
